import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('.sites-runtime/research.json','utf8'));
const titles=['Stovetop mac & cheese','Classic sloppy joes','Chicken noodle soup','Sunday meatloaf','Beef & bean chili','Buffalo chicken wings','All-American apple pie','Fluffy pancakes','Fudge brownies','Cream drop biscuits'];
const categories=['Dinner','Dinner','Dinner','Dinner','Dinner','Dinner','Baking','Breakfast','Baking','Baking'];
const ingredients=[['Macaroni','Cheddar','Milk','Butter','Flour','Paprika'],['Ground beef','Onion','Bell pepper','Tomato sauce','Hamburger buns'],['Chicken','Egg noodles','Carrots','Celery','Chicken broth'],['Ground beef','Breadcrumbs','Egg','Milk','Onion','Ketchup'],['Ground beef','Kidney beans','Black beans','Tomatoes','Chili powder'],['Chicken wings','Hot sauce','Butter','Cornstarch','Paprika'],['Apples','Flour','Butter','Shortening','Sugar','Cinnamon'],['Flour','Eggs','Milk','Butter','Baking powder'],['Cocoa','Chocolate chips','Butter','Eggs','Sugar','Flour'],['Self-rising flour','Heavy cream','Salt']];
const descriptions=['A silky cheddar sauce, a pot of pasta, and a very good reason to stay in.','A tangy tomato-and-beef filling piled into a toasted bun. Napkins encouraged.','Slow-simmered chicken, tender noodles, and vegetables in a comforting broth.','A family-table classic with a sweet and tangy glaze.','A hearty pot of beef, two kinds of beans, and warming spices.','Oven-baked wings finished with a buttery, spicy Buffalo sauce.','Spiced apples tucked beneath a golden pastry crust.','Golden edges, soft centers. Make a stack for a slow morning.','Deep chocolate flavor with a soft center and a glossy top.','A simple two-ingredient dough for tender, warm biscuits.'];
const steps=[['Boil the macaroni, then drain. Cook butter and flour together to make the base for the sauce.','Gradually whisk in milk and simmer until thick. Remove from the heat, season, and melt in the cheddar in batches.','Fold in the pasta and serve warm.'],['Brown the beef, drain excess fat, and soften the chopped vegetables in the same skillet.','Mix in the tomato ingredients, vinegar, sugar, and seasonings. Simmer briefly until combined.','Spoon the filling into toasted buns.'],['Soften the vegetables, then add the garlic, herbs, chicken, and broth.','Simmer gently, covered, until the chicken can be shredded. Remove it and shred with two forks.','Cook noodles in the broth, then return the chicken and finish with parsley.'],['Combine the beef with the egg mixture, seasoned breadcrumbs, and onion without overworking it.','Shape into a loaf on a rimmed baking dish. Spread the ketchup glaze over the top and sides.','Bake at 350°F according to the full recipe, checking the internal temperature. Rest before slicing.'],['Soften onion and garlic in oil, then brown the beef.','Stir in drained beans, tomatoes, tomato paste, water, and spices.','Cover and simmer for at least 30 minutes, stirring occasionally. Adjust the seasoning before serving.'],['Dry the wings and coat with oil, cornstarch, and seasonings. Arrange on a rack over a baking sheet.','Bake at 400°F, turning partway through, following the full recipe for doneness.','Warm the butter with hot sauce and seasonings, then toss with the cooked wings.'],['Make and chill the pastry. Toss sliced apples with lemon, sugar, spices, and thickener.','Line the pie dish, add the filling and butter, then cover with pastry and cut steam vents.','Bake initially at 425°F, then lower to 375°F as directed. Let the filling bubble and cool the pie fully before slicing.'],['Beat eggs and milk until foamy, then add melted butter. Mix the dry ingredients separately.','Gently combine and rest the batter for 15 minutes. Heat a lightly greased griddle.','Cook quarter-cup portions, flipping when bubbles break on the surface. Serve straight away.'],['Combine the eggs, cocoa, and flavorings. Warm the butter with sugar, then stir it into the cocoa mixture.','Fold in flour and chocolate chips. Spread in a prepared 9 × 13-inch pan.','Bake at 350°F for about 28–32 minutes. Cool before cutting.'],['Heat the oven to 450°F. Mix self-rising flour with heavy cream to form a cohesive dough.','Scoop onto a lined baking sheet, leaving room between biscuits. Brush the tops with liquid.','Bake about 10 minutes until golden and cooked through. Serve warm.']];
const data=raw.map((r,i)=>({id:i+1,title:titles[i],category:categories[i],minutes:[25,30,105,65,50,70,120,45,40,15][i],yield:['4 servings','5 servings','8 servings','7 slices','6 servings','4 servings','One 9-inch pie','12 pancakes','24 brownies','12 biscuits'][i],description:descriptions[i],ingredients:ingredients[i],steps:steps[i],source:r.url,publisher:i<6?'Budget Bytes':'King Arthur Baking',image:Array.isArray(r.recipe.image)?r.recipe.image[2]:r.recipe.image.url}));
fs.mkdirSync('src',{recursive:true});fs.writeFileSync('src/recipes.json',JSON.stringify(data,null,2));
